name: twenty-seven revolutions around the sun
favicon: null
layout_spectrum: 0.99526
typography_spectrum: 0.24194
title: twenty-seven revolutions around the sun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.863250182243064
purpose: []
