name: twenty-seven revolutions around the sun
favicon: null
layout_spectrum: 0.49226
typography_spectrum: 0.59284
title: twenty-seven revolutions around the sun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#daad75'
    - '#cf5290'
    - '#f084b7'
    - '#94215d'
    - '#cb7a6d'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.863250182243064
purpose: []
